---
- name: Delete rdpserver
  hosts: demo_servers
  become: True
  vars:
    ansible_python_interpreter: python3      




  tasks:

    - name: delete rdpserver
      docker_container:
        name: rdpserver
        state: absent

    - name: delete rdpserver base image
      docker_image:
        #name: rdpserver
        name: mkarnowski/diab
        #tag: latest
        tag: rdpserver
        state: absent
