{
 "title": "01-Summary",
 "tags": [
  "network",
  "avi"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "location", "query": "network-script.avi.*" },
   { "name": "environment", "query": "network-script.avi.$location.*" },
   {
    "name": "device",
    "query": "network-script.avi.$location.$environment.*"
   }
  ]
 },
 "panels": [
  {
   "title": "VS UP",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "alias(network-script.avi.$location.$environment.$device.virtualservice.status_up, 'VS Up')"
    }
   ]
  },
  {
   "title": "CPS",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "alias(sumSeries(network-script.avi.$location.$environment.$device.virtualservice.*.l4_client_avg_new_established_conns), 'connections')"
    }
   ]
  },
  {
   "title": "SSL TPS",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "sumSeries(network-script.avi.$location.$environment.$device.virtualservice.*.l7_client_avg_ssl_handshakes_new)"
    }
   ]
  },
  {
   "title": "Total Bandwidth",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 0 },
   "format": "bps",
   "valueName": "current",
   "targets": [
    {
     "target": "alias(sumSeries(network-script.avi.$location.$environment.$device.serviceengine.*.se_if_avg_bandwidth), 'Total SE Bandwidth')"
    }
   ]
  },
  {
   "title": "Controller CPU%",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(network-script.avi.$location.$environment.$device.controller.*.controller_stats_avg_cpu_usage, 6)"
    }
   ]
  },
  {
   "title": "Controller Mem%",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(network-script.avi.$location.$environment.$device.controller.*.controller_stats_avg_mem_usage, 6)"
    }
   ]
  },
  {
   "title": "Total Number of VS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(sumSeries(network-script.avi.$location.$environment.$device.serviceengine.*.vs_count), 'Virtual Services Deployed')"
    },
    {
     "target": "alias(network-script.avi.$location.$environment.$device.virtualservice.count, 'Virtual Services Configured')"
    }
   ]
  },
  {
   "title": "Total Number of Service Engines",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(network-script.avi.$location.$environment.$device.serviceengine.count, 'Service Engines')"
    }
   ]
  },
  {
   "title": "Avi Version - Current Version = 1",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 10 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode(currentAbove(network-script.avi.$location.$environment.$device.current_version.*, 0), 6)"
    }
   ]
  },
  {
   "title": "Total Virtual Server Status",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(network-script.avi.$location.$environment.$device.virtualservice.status_up, 'VS Up')"
    },
    {
     "target": "alias(network-script.avi.$location.$environment.$device.virtualservice.status_down, 'VS Down')"
    }
   ]
  },
  {
   "title": "Top 5 SE CPU %",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 17 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "aliasByNode(highestCurrent(network-script.avi.$location.$environment.$device.serviceengine.*.se_stats_avg_cpu_usage, 5), 6)"
    }
   ]
  },
  {
   "title": "Total VS Bandwidth",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 17 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "target": "alias(scale(sumSeries(network-script.avi.$location.$environment.$device.virtualservice.*.l4_client_avg_rx_bytes), 8), 'Total RX Bandwidth')"
    },
    {
     "target": "alias(scale(sumSeries(network-script.avi.$location.$environment.$device.virtualservice.*.l4_client_avg_tx_bytes), 8), 'Total TX Bandwidth')"
    }
   ]
  },
  {
   "title": "% of VS UP",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "alias(asPercent(network-script.avi.$location.$environment.$device.virtualservice.status_up, #B), 'VS UP%')"
    }
   ]
  },
  {
   "title": "Total Connections Per Second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(sumSeries(network-script.avi.$location.$environment.$device.virtualservice.*.l4_client_avg_new_established_conns), 'connections')"
    }
   ]
  },
  {
   "title": "Total Concurrent Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(sumSeries(network-script.avi.$location.$environment.$device.virtualservice.*.l4_client_avg_complete_conns), ' connections')"
    }
   ]
  },
  {
   "title": "Active Cluster Members",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(network-script.avi.$location.$environment.$device.cluster.active_members)"
    }
   ]
  },
  {
   "title": "Cluster Roles: 1 == Leader",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "short", "label": "Role" }
   ],
   "targets": [
    {
     "target": "aliasByNode(network-script.avi.$location.$environment.$device.cluster.*.role, 6)"
    }
   ]
  },
  {
   "title": "% of Licensed Cores Used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(network-script.avi.$location.$environment.$device.licensing.percentage_used)"
    }
   ]
  },
  {
   "title": "TOTAL SE BW",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "target": "alias(sumSeries(network-script.avi.$location.$environment.$device.serviceengine.*.se_if_avg_bandwidth), 'Total SE Bandwidth')"
    }
   ]
  }
 ]
}