{
 "title": "05-Virtual Services Specific",
 "tags": [
  "network",
  "avi"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "location", "query": "network-script.avi.*" },
   { "name": "environment", "query": "network-script.avi.$location.*" },
   {
    "name": "device",
    "query": "network-script.avi.$location.$environment.*"
   },
   {
    "name": "vs",
    "query": "network-script.avi.$location.$environment.$device.virtualservice.*"
   }
  ]
 },
 "panels": [
  {
   "title": "Bandwidth",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 0 },
   "format": "bps",
   "valueName": "current",
   "targets": [
    {
     "target": "aliasByNode(network-script.avi.$location.$environment.$device.virtualservice.$vs.l4_client_avg_bandwidth, 6)"
    }
   ]
  },
  {
   "title": "CPS",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 5, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "network-script.avi.$location.$environment.$device.virtualservice.$vs.l4_client_avg_new_established_conns"
    }
   ]
  },
  {
   "title": "Concurrent Conns",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 9, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "network-script.avi.$location.$environment.$device.virtualservice.$vs.l4_client_avg_complete_conns"
    }
   ]
  },
  {
   "title": "SSL TPS",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 14, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "aliasByMetric(network-script.avi.$location.$environment.$device.virtualservice.$vs.l7_client_avg_ssl_handshakes_new)"
    }
   ]
  },
  {
   "title": "Healthscore",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "aliasByMetric(network-script.avi.$location.$environment.$device.virtualservice.$vs.healthscore)"
    }
   ]
  },
  {
   "title": "End to End Timing",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(network-script.avi.$location.$environment.$device.virtualservice.$vs.l4_client_avg_total_rtt, 'Client RTT')"
    },
    {
     "target": "alias(network-script.avi.$location.$environment.$device.virtualservice.$vs.l4_server_avg_total_rtt, 'Server RTT')"
    },
    {
     "target": "alias(network-script.avi.$location.$environment.$device.virtualservice.$vs.l7_server_avg_application_response_time, 'App Response')"
    },
    {
     "target": "alias(network-script.avi.$location.$environment.$device.virtualservice.$vs.l7_client_avg_client_data_transfer_time, 'Data Transfer')"
    }
   ]
  },
  {
   "title": "VS Bandwidth",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "target": "aliasByNode(network-script.avi.$location.$environment.$device.virtualservice.$vs.l4_client_avg_bandwidth, 6)"
    }
   ]
  },
  {
   "title": "Connections Per Second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(network-script.avi.$location.$environment.$device.virtualservice.$vs.l4_client_avg_new_established_conns, 6)"
    }
   ]
  },
  {
   "title": "Concurrent Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(network-script.avi.$location.$environment.$device.virtualservice.$vs.l4_client_avg_complete_conns, 6)"
    }
   ]
  },
  {
   "title": "VS Oper Status : 1 == UP",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(network-script.avi.$location.$environment.$device.virtualservice.$vs.oper_status)"
    }
   ]
  },
  {
   "title": "Avg Server Side Latency (ms)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 17 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(network-script.avi.$location.$environment.$device.virtualservice.$vs.l7_server_avg_resp_latency)"
    }
   ]
  },
  {
   "title": "Pool Members",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(network-script.avi.$location.$environment.$device.virtualservice.$vs.pool.*.pool_members_up, 8, 9)"
    },
    {
     "target": "aliasByNode(network-script.avi.$location.$environment.$device.virtualservice.$vs.pool.*.pool_members_enabled, 8, 9)"
    },
    {
     "target": "aliasByNode(network-script.avi.$location.$environment.$device.virtualservice.$vs.pool.*.pool_members, 8, 9)"
    }
   ]
  },
  {
   "title": "RX Packets Per Second",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(network-script.avi.$location.$environment.$device.virtualservice.$vs.l4_client_avg_rx_pkts, 6)"
    }
   ]
  },
  {
   "title": "TX Packets Per Second",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(network-script.avi.$location.$environment.$device.virtualservice.$vs.l4_client_avg_tx_pkts, 6)"
    }
   ]
  },
  {
   "title": "VS Healthscore",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(network-script.avi.$location.$environment.$device.virtualservice.$vs.healthscore, 6)"
    }
   ]
  },
  {
   "title": "Hosted on Service Engines",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(currentAbove(network-script.avi.$location.$environment.$device.virtualservice.$vs.serviceengine.*, 0))"
    }
   ]
  },
  {
   "title": "Average Client Lossy Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(network-script.avi.$location.$environment.$device.virtualservice.$vs.l4_client_avg_lossy_connections)"
    }
   ]
  },
  {
   "title": "SSL Statistics /sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(network-script.avi.$location.$environment.$device.virtualservice.$vs.l7_client_avg_ssl_handshakes_new)"
    },
    {
     "target": "aliasByMetric(network-script.avi.$location.$environment.$device.virtualservice.$vs.l7_client_avg_ssl_connections)"
    }
   ]
  },
  {
   "title": "4xx 5xx Status Codes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(network-script.avi.$location.$environment.$device.virtualservice.$vs.l7_client_avg_resp_4xx_avi_errors)"
    },
    {
     "target": "aliasByMetric(network-script.avi.$location.$environment.$device.virtualservice.$vs.l7_client_avg_resp_5xx_avi_errors)"
    },
    {
     "target": "aliasByMetric(network-script.avi.$location.$environment.$device.virtualservice.$vs.l7_client_avg_resp_4xx)"
    },
    {
     "target": "aliasByMetric(network-script.avi.$location.$environment.$device.virtualservice.$vs.l7_client_avg_resp_5xx)"
    },
    {
     "target": "aliasByMetric(network-script.avi.$location.$environment.$device.virtualservice.$vs.l7_server_avg_resp_4xx)"
    },
    {
     "target": "aliasByMetric(network-script.avi.$location.$environment.$device.virtualservice.$vs.l7_server_avg_resp_5xx)"
    }
   ]
  },
  {
   "title": "Client Side Open Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(network-script.avi.$location.$environment.$device.virtualservice.$vs.l4_client_max_open_conns)"
    }
   ]
  },
  {
   "title": "Virtual Service ApDex  Values",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(network-script.avi.$location.$environment.$device.virtualservice.$vs.l4_client_apdexc)"
    },
    {
     "target": "aliasByMetric(network-script.avi.$location.$environment.$device.virtualservice.$vs.l4_server_apdexc)"
    },
    {
     "target": "aliasByMetric(network-script.avi.$location.$environment.$device.virtualservice.$vs.l7_client_apdexr)"
    },
    {
     "target": "aliasByMetric(network-script.avi.$location.$environment.$device.virtualservice.$vs.l7_server_apdexr)"
    }
   ]
  },
  {
   "title": "Pool Member - Avg Bandwidth",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 65 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "target": "aliasByNode(network-script.avi.$location.$environment.$device.virtualservice.$vs.pool.*.*.l4_server_avg_bandwidth, 8, 9)"
    }
   ]
  },
  {
   "title": "Pool Member - Open Conns",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 65 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(network-script.avi.$location.$environment.$device.virtualservice.$vs.pool.*.*.l4_server_avg_open_conns, 8, 9)"
    }
   ]
  },
  {
   "title": "Pool Member - Total TX packets from",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 72 },
   "targets": [
    {
     "target": "aliasByNode(scale(network-script.avi.$location.$environment.$device.virtualservice.$vs.pool.*.*.l4_server_avg_tx_pkts, 60), 8, 9)"
    }
   ]
  },
  {
   "title": "Pool Member - Total RX packets from",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 72 },
   "targets": [
    {
     "target": "aliasByNode(scale(network-script.avi.$location.$environment.$device.virtualservice.$vs.pool.*.*.l4_server_avg_rx_pkts, 60), 8, 9)"
    }
   ]
  },
  {
   "title": "Pool Member - Total TX Bytes to",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 72 },
   "targets": [
    {
     "target": "aliasByNode(scale(network-script.avi.$location.$environment.$device.virtualservice.$vs.pool.*.*.l4_server_avg_tx_bytes, 60), 8, 9)"
    }
   ]
  },
  {
   "title": "Pool Member - Total RX Bytes from",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 72 },
   "targets": [
    {
     "target": "aliasByNode(scale(network-script.avi.$location.$environment.$device.virtualservice.$vs.pool.*.*.l4_server_avg_rx_bytes, 60), 8, 9)"
    }
   ]
  }
 ]
}