/*{"version":"20977131","created":"2013-11-07T16:26:13Z","mac":"1:d3fb302a79aeba9fb1b0bff19d057daa56c004a6862a688e8c532867dd8111fa","k":"1.6.4"}*/
/*
 * For font license information, see the CSS file loaded by this JavaScript.
 */
;(function(window,document,undefined){
var h=!0,k=null,l=!1;function m(a){return function(){return this[a]}}var aa=this;function ba(a,b){var c=a.split("."),d=aa;!(c[0]in d)&&d.execScript&&d.execScript("var "+c[0]);for(var e;c.length&&(e=c.shift());)!c.length&&void 0!==b?d[e]=b:d=d[e]?d[e]:d[e]={}}function ca(a,b,c){return a.call.apply(a.bind,arguments)}
function da(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}}function n(a,b,c){n=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?ca:da;return n.apply(k,arguments)}var ea=Date.now||function(){return+new Date};
function ga(a,b){this.Y=a;this.P=b||a;this.D=this.P.document}ga.prototype.createElement=function(a,b,c){a=this.D.createElement(a);if(b)for(var d in b)b.hasOwnProperty(d)&&("style"==d?a.style.cssText=b[d]:a.setAttribute(d,b[d]));c&&a.appendChild(this.D.createTextNode(c));return a};function q(a,b,c){a=a.D.getElementsByTagName(b)[0];a||(a=document.documentElement);a&&a.lastChild&&a.insertBefore(c,a.lastChild)}function ha(a,b){function c(){a.D.body?b():setTimeout(c,0)}c()}
function r(a,b){for(var c=a.className.split(/\s+/),d=0,e=c.length;d<e;d++)if(c[d]==b)return;c.push(b);a.className=c.join(" ").replace(/\s+/g," ").replace(/^\s+|\s+$/,"")}function s(a,b){for(var c=a.className.split(/\s+/),d=[],e=0,f=c.length;e<f;e++)c[e]!=b&&d.push(c[e]);a.className=d.join(" ").replace(/\s+/g," ").replace(/^\s+|\s+$/,"")}function ia(a,b){for(var c=a.className.split(/\s+/),d=0,e=c.length;d<e;d++)if(c[d]==b)return h;return l}
function ja(a){var b=a.P.location.protocol;"about:"==b&&(b=a.Y.location.protocol);return"https:"==b?"https:":"http:"}
function ka(a,b,c){var d=a.D.getElementsByTagName("head")[0];if(d){var e=a.createElement("script",{src:b}),f=l;e.onload=e.onreadystatechange=function(){if(!f&&(!this.readyState||"loaded"==this.readyState||"complete"==this.readyState))f=h,c&&c(k),e.onload=e.onreadystatechange=k,"HEAD"==e.parentNode.tagName&&d.removeChild(e)};d.appendChild(e);window.setTimeout(function(){f||(f=h,c&&c(Error("Script load timeout")))},5E3)}}function t(a,b,c){this.Na=a;this.aa=b;this.Ma=c}
ba("internalWebfont.BrowserInfo",t);t.prototype.Aa=m("Na");t.prototype.hasWebFontSupport=t.prototype.Aa;t.prototype.Ba=m("aa");t.prototype.hasWebKitFallbackBug=t.prototype.Ba;t.prototype.Ca=m("Ma");t.prototype.hasWebKitMetricsBug=t.prototype.Ca;function u(a,b,c,d){this.e=a!=k?a:k;this.m=b!=k?b:k;this.C=c!=k?c:k;this.j=d!=k?d:k}var la=/^([0-9]+)(?:[\._-]([0-9]+))?(?:[\._-]([0-9]+))?(?:[\._+-]?(.*))?$/;
function v(a,b){return a.e>b.e||a.e===b.e&&a.m>b.m||a.e===b.e&&a.m===b.m&&a.C>b.C?1:a.e<b.e||a.e===b.e&&a.m<b.m||a.e===b.e&&a.m===b.m&&a.C<b.C?-1:0}function w(a,b){return 0===v(a,b)||1===v(a,b)}u.prototype.toString=function(){return[this.e,this.m||"",this.C||"",this.j||""].join("")};
function y(a){a=la.exec(a);var b=k,c=k,d=k,e=k;a&&(a[1]!==k&&a[1]&&(b=parseInt(a[1],10)),a[2]!==k&&a[2]&&(c=parseInt(a[2],10)),a[3]!==k&&a[3]&&(d=parseInt(a[3],10)),a[4]!==k&&a[4]&&(e=/^[0-9]+$/.test(a[4])?parseInt(a[4],10):a[4]));return new u(b,c,d,e)}function A(a,b,c,d,e,f,g,j,p,x,fa){this.Q=a;this.n=b;this.La=c;this.u=d;this.z=e;this.qa=f;this.k=g;this.h=j;this.Ha=p;this.N=x;this.t=fa}ba("internalWebfont.UserAgent",A);A.prototype.getName=m("Q");A.prototype.getName=A.prototype.getName;
A.prototype.za=m("La");A.prototype.getVersion=A.prototype.za;A.prototype.va=m("u");A.prototype.getEngine=A.prototype.va;A.prototype.wa=m("qa");A.prototype.getEngineVersion=A.prototype.wa;A.prototype.xa=m("k");A.prototype.getPlatform=A.prototype.xa;A.prototype.ya=m("Ha");A.prototype.getPlatformVersion=A.prototype.ya;A.prototype.ua=m("N");A.prototype.getDocumentMode=A.prototype.ua;A.prototype.ta=m("t");A.prototype.getBrowserInfo=A.prototype.ta;function ma(a,b){this.c=a;this.M=b}
var na=new A("Unknown",new u,"Unknown","Unknown",new u,"Unknown","Unknown",new u,"Unknown",void 0,new t(l,l,l));
ma.prototype.parse=function(){var a;if(-1!=this.c.indexOf("MSIE")||-1!=this.c.indexOf("Trident/")){a=B(this);var b=C(this),c=y(b),d=k,e=k,f=k,g=k,j=D(this.c,/Trident\/([\d\w\.]+)/,1),p=E(this.M),d=-1!=this.c.indexOf("MSIE")?D(this.c,/MSIE ([\d\w\.]+)/,1):D(this.c,/rv:([\d\w\.]+)/,1),e=y(d);""!=j?(f="Trident",g=y(j)):(f="Unknown",g=new u,j="Unknown");a=new A("MSIE",e,d,f,g,j,a,c,b,p,new t("Windows"==a&&6<=e.e||"Windows Phone"==a&&8<=c.e,l,l))}else if(-1!=this.c.indexOf("Opera"))a:if(a="Unknown",b=
D(this.c,/Presto\/([\d\w\.]+)/,1),c=y(b),d=C(this),e=y(d),f=E(this.M),c.e!==k?a="Presto":(-1!=this.c.indexOf("Gecko")&&(a="Gecko"),b=D(this.c,/rv:([^\)]+)/,1),c=y(b)),-1!=this.c.indexOf("Opera Mini/"))g=D(this.c,/Opera Mini\/([\d\.]+)/,1),j=y(g),a=new A("OperaMini",j,g,a,c,b,B(this),e,d,f,new t(l,l,l));else{if(-1!=this.c.indexOf("Version/")&&(g=D(this.c,/Version\/([\d\.]+)/,1),j=y(g),j.e!==k)){a=new A("Opera",j,g,a,c,b,B(this),e,d,f,new t(10<=j.e,l,l));break a}g=D(this.c,/Opera[\/ ]([\d\.]+)/,1);
j=y(g);a=j.e!==k?new A("Opera",j,g,a,c,b,B(this),e,d,f,new t(10<=j.e,l,l)):new A("Opera",new u,"Unknown",a,c,b,B(this),e,d,f,new t(l,l,l))}else/OPR\/[\d.]+/.test(this.c)?a=qa(this):/AppleWeb(K|k)it/.test(this.c)?a=qa(this):-1!=this.c.indexOf("Gecko")?(a="Unknown",b=new u,c="Unknown",d=C(this),e=y(d),f=l,-1!=this.c.indexOf("Firefox")?(a="Firefox",c=D(this.c,/Firefox\/([\d\w\.]+)/,1),b=y(c),f=3<=b.e&&5<=b.m):-1!=this.c.indexOf("Mozilla")&&(a="Mozilla"),g=D(this.c,/rv:([^\)]+)/,1),j=y(g),f||(f=1<j.e||
1==j.e&&9<j.m||1==j.e&&9==j.m&&2<=j.C||g.match(/1\.9\.1b[123]/)!=k||g.match(/1\.9\.1\.[\d\.]+/)!=k),a=new A(a,b,c,"Gecko",j,g,B(this),e,d,E(this.M),new t(f,l,l))):a=na;return a};function B(a){var b=D(a.c,/(iPod|iPad|iPhone|Android|Windows Phone|BB\d{2}|BlackBerry)/,1);if(""!=b)return/BB\d{2}/.test(b)&&(b="BlackBerry"),b;a=D(a.c,/(Linux|Mac_PowerPC|Macintosh|Windows|CrOS)/,1);return""!=a?("Mac_PowerPC"==a&&(a="Macintosh"),a):"Unknown"}
function C(a){var b=D(a.c,/(OS X|Windows NT|Android) ([^;)]+)/,2);if(b||(b=D(a.c,/Windows Phone( OS)? ([^;)]+)/,2))||(b=D(a.c,/(iPhone )?OS ([\d_]+)/,2)))return b;if(b=D(a.c,/(?:Linux|CrOS) ([^;)]+)/,1))for(var b=b.split(/\s/),c=0;c<b.length;c+=1)if(/^[\d\._]+$/.test(b[c]))return b[c];return(a=D(a.c,/(BB\d{2}|BlackBerry).*?Version\/([^\s]*)/,2))?a:"Unknown"}
function qa(a){var b=B(a),c=C(a),d=y(c),e=D(a.c,/AppleWeb(?:K|k)it\/([\d\.\+]+)/,1),f=y(e),g="Unknown",j=new u,p="Unknown",x=l;/OPR\/[\d.]+/.test(a.c)?g="Opera":-1!=a.c.indexOf("Chrome")||-1!=a.c.indexOf("CrMo")||-1!=a.c.indexOf("CriOS")?g="Chrome":/Silk\/\d/.test(a.c)?g="Silk":"BlackBerry"==b||"Android"==b?g="BuiltinBrowser":-1!=a.c.indexOf("PhantomJS")?g="PhantomJS":-1!=a.c.indexOf("Safari")?g="Safari":-1!=a.c.indexOf("AdobeAIR")&&(g="AdobeAIR");"BuiltinBrowser"==g?p="Unknown":"Silk"==g?p=D(a.c,
/Silk\/([\d\._]+)/,1):"Chrome"==g?p=D(a.c,/(Chrome|CrMo|CriOS)\/([\d\.]+)/,2):-1!=a.c.indexOf("Version/")?p=D(a.c,/Version\/([\d\.\w]+)/,1):"AdobeAIR"==g?p=D(a.c,/AdobeAIR\/([\d\.]+)/,1):"Opera"==g?p=D(a.c,/OPR\/([\d.]+)/,1):"PhantomJS"==g&&(p=D(a.c,/PhantomJS\/([\d.]+)/,1));j=y(p);x="AdobeAIR"==g?2<j.e||2==j.e&&5<=j.m:"BlackBerry"==b?10<=d.e:"Android"==b?2<d.e||2==d.e&&1<d.m:526<=f.e||525<=f.e&&13<=f.m;return new A(g,j,p,"AppleWebKit",f,e,b,d,c,E(a.M),new t(x,536>f.e||536==f.e&&11>f.m,"iPhone"==
b||"iPad"==b||"iPod"==b||"Macintosh"==b))}function D(a,b,c){return(a=a.match(b))&&a[c]?a[c]:""}function E(a){if(a.documentMode)return a.documentMode}function ra(a){this.Fa=a||"-"}ra.prototype.j=function(a){for(var b=[],c=0;c<arguments.length;c++)b.push(arguments[c].replace(/[\W_]+/g,"").toLowerCase());return b.join(this.Fa)};function sa(a,b,c){this.g=a;this.l=b;this.T=c;this.p="wf";this.o=new ra("-")}
function ta(a){s(a.l,a.o.j(a.p,"loading"));ia(a.l,a.o.j(a.p,"active"))||r(a.l,a.o.j(a.p,"inactive"));F(a,"inactive")}function F(a,b,c){if(a.T[b])if(c)a.T[b](c.getName(),G(c));else a.T[b]()}function H(a,b){this.Q=a;this.ba=4;this.R="n";var c=(b||"n4").match(/^([nio])([1-9])$/i);c&&(this.R=c[1],this.ba=parseInt(c[2],10))}H.prototype.getName=m("Q");function G(a){return a.R+a.ba}function J(a,b){this.g=a;this.I=b;this.w=this.g.createElement("span",{"aria-hidden":"true"},this.I)}
function ua(a,b){var c;c=[];for(var d=b.Q.split(/,\s*/),e=0;e<d.length;e++){var f=d[e].replace(/['"]/g,"");-1==f.indexOf(" ")?c.push(f):c.push("'"+f+"'")}c=c.join(",");d="normal";e=b.ba+"00";"o"===b.R?d="oblique":"i"===b.R&&(d="italic");a.w.style.cssText="position:absolute;top:-999px;left:-999px;font-size:300px;width:auto;height:auto;line-height:normal;margin:0;padding:0;font-variant:normal;white-space:nowrap;font-family:"+c+";"+("font-style:"+d+";font-weight:"+e+";")}
function va(a){q(a.g,"body",a.w)}J.prototype.remove=function(){var a=this.w;a.parentNode&&a.parentNode.removeChild(a)};function wa(a,b,c,d,e,f,g,j){this.ca=a;this.Da=b;this.g=c;this.v=d;this.I=j||"BESbswy";this.t=e;this.J={};this.Z=f||5E3;this.ka=g||k;this.H=this.G=k;a=new J(this.g,this.I);va(a);for(var p in K)K.hasOwnProperty(p)&&(ua(a,new H(K[p],G(this.v))),this.J[K[p]]=a.w.offsetWidth);a.remove()}var K={Ua:"serif",Ta:"sans-serif",Qa:"monospace"};
wa.prototype.start=function(){this.G=new J(this.g,this.I);va(this.G);this.H=new J(this.g,this.I);va(this.H);this.Ja=ea();ua(this.G,new H(this.v.getName()+",serif",G(this.v)));ua(this.H,new H(this.v.getName()+",sans-serif",G(this.v)));xa(this)};function ya(a,b,c){for(var d in K)if(K.hasOwnProperty(d)&&b===a.J[K[d]]&&c===a.J[K[d]])return h;return l}
function xa(a){var b=a.G.w.offsetWidth,c=a.H.w.offsetWidth;b===a.J.serif&&c===a.J["sans-serif"]||a.t.aa&&ya(a,b,c)?ea()-a.Ja>=a.Z?a.t.aa&&ya(a,b,c)&&(a.ka===k||a.ka.hasOwnProperty(a.v.getName()))?za(a,a.ca):za(a,a.Da):setTimeout(n(function(){xa(this)},a),25):za(a,a.ca)}function za(a,b){a.G.remove();a.H.remove();b(a.v)}function L(a,b,c,d){this.g=b;this.A=c;this.V=0;this.na=this.ja=l;this.Z=d;this.t=a.t}
L.prototype.$=function(a,b,c,d){if(0===a.length&&d)ta(this.A);else{this.V+=a.length;d&&(this.ja=d);for(d=0;d<a.length;d++){var e=a[d],f=b[e.getName()],g=this.A,j=e;r(g.l,g.o.j(g.p,j.getName(),G(j).toString(),"loading"));F(g,"fontloading",j);(new wa(n(this.ra,this),n(this.sa,this),this.g,e,this.t,this.Z,c,f)).start()}}};
L.prototype.ra=function(a){var b=this.A;s(b.l,b.o.j(b.p,a.getName(),G(a).toString(),"loading"));s(b.l,b.o.j(b.p,a.getName(),G(a).toString(),"inactive"));r(b.l,b.o.j(b.p,a.getName(),G(a).toString(),"active"));F(b,"fontactive",a);this.na=h;Aa(this)};L.prototype.sa=function(a){var b=this.A;s(b.l,b.o.j(b.p,a.getName(),G(a).toString(),"loading"));ia(b.l,b.o.j(b.p,a.getName(),G(a).toString(),"active"))||r(b.l,b.o.j(b.p,a.getName(),G(a).toString(),"inactive"));F(b,"fontinactive",a);Aa(this)};
function Aa(a){0==--a.V&&a.ja&&(a.na?(a=a.A,s(a.l,a.o.j(a.p,"loading")),s(a.l,a.o.j(a.p,"inactive")),r(a.l,a.o.j(a.p,"active")),F(a,"active")):ta(a.A))}function M(a,b){this.Ia=a;this.fa=b}function Ba(a){for(var b=a.Ia.join(","),c=[],d=0;d<a.fa.length;d++){var e=a.fa[d];c.push(e.name+":"+e.value+";")}return b+"{"+c.join("")+"}"}function Ca(a){this.g=a}Ca.prototype.toString=function(){return encodeURIComponent(this.g.P.location.hostname||this.g.Y.location.hostname)};
function Da(a,b){this.q=a;this.s=b}Da.prototype.toString=function(){for(var a=[],b=0;b<this.s.length;b++)for(var c=this.s[b],d=c.B(),c=c.B(this.q),e=0;e<d.length;e++){var f;a:{for(f=0;f<c.length;f++)if(d[e]===c[f]){f=h;break a}f=l}a.push(f?1:0)}a=a.join("");a=a.replace(/^0+/,"");b=[];for(d=a.length;0<d;d-=4)c=a.slice(0>d-4?0:d-4,d),b.unshift(parseInt(c,2).toString(16));return b.join("")};function N(a){this.Ka=a}
N.prototype.j=function(a,b){var c=b||{},d=this.Ka.replace(/\{\/?([^*}]*)(\*?)\}/g,function(a,b,d){return d&&c[b]?"/"+c[b].join("/"):c[b]||""});d.match(/^\/\//)&&(d=(a?"https:":"http:")+d);return d.replace(/\/*\?*($|\?)/,"$1")};function O(a,b,c,d){this.F=a;this.O=b;this.Xa=c;this.Ya=d;this.ha={};this.ga={}}O.prototype.B=function(a){return a?(this.ha[a]||this.O).slice(0):this.O.slice(0)};O.prototype.$=function(a,b,c){var d=[],e={};Ea(this,b,d,e);a(d,e,c)};
function Ea(a,b,c,d){c.push(a.F);d[a.F]=a.B(b);a=a.ga[b]||[];for(b=0;b<a.length;b++){for(var e=a[b],f=e.F,g=l,j=0;j<c.length;j++)c[j]==f&&(g=h);g||(c.push(f),d[f]=e.B())}}function Fa(a,b){this.F=a;this.O=b}Fa.prototype.B=m("O");function Ga(){this.pa=this.Oa=this.K=this.W=this.Ea=h}function P(a){return"Windows"===a.k}function Q(a){return P(a)&&0===v(a.h,new u(5,1))||P(a)&&0===v(a.h,new u(5,2))||P(a)&&0===v(a.h,new u(6,0))||P(a)&&w(a.h,new u(6,1))}
function R(a){return"Macintosh"===a.k&&(w(a.h,new u(10,4))||a.h.e===k)}function Ha(a,b){return b.Ea&&("iPhone"===a.k||"iPod"===a.k)}function Ia(a,b){return Ha(a,b)&&w(a.h,new u(4,2))&&-1===v(a.h,new u(5))}function Ja(a,b){return b.W&&"iPad"===a.k&&w(a.h,new u(4,2))&&-1===v(a.h,new u(5))}function S(a,b){return b.K&&"Android"===a.k}function Ka(a,b){return S(a,b)&&w(a.h,new u(2,2))&&-1===v(a.h,new u(3,1))}function La(a,b){return S(a,b)&&w(a.h,new u(3,1))&&-1===v(a.h,new u(4,1))}
function U(a){return"Linux"===a.k||"Ubuntu"===a.k}function Ma(a){return"Gecko"===a.u&&0===v(a.z,new u(1,9,1))&&!/^b[1-3]$/.test(a.z.j||"")}function Na(a){return"Safari"===a.getName()&&"AppleWebKit"===a.u||"Unknown"===a.getName()&&"AppleWebKit"===a.u&&("iPhone"===a.k||"iPad"===a.k||"iPod"===a.k)}function Oa(a){return"Safari"===a.getName()&&"AppleWebKit"===a.u&&w(a.z,new u(525,13))&&-1===v(a.z,new u(534,50))}function Pa(a){return"Opera"===a.getName()&&w(a.n,new u(10,54))&&-1===v(a.n,new u(11,10))}
function Qa(a){return"BuiltinBrowser"===a.getName()}function Ra(a){this.ma=a}function Sa(a,b){return b}
var Ta={Ra:"a",Sa:"b",Wa:"d",Va:"f",Pa:"i"},Ua={a:function(a,b){return Oa(a)&&Q(a)||Qa(a)&&(Ka(a,b)||S(a,b)&&w(a.h,new u(4,1)))||b.K&&"Silk"===a.getName()&&-1===v(a.n,new u(2))&&(Ka(a,b)||R)||b.K&&"Silk"===a.getName()&&w(a.n,new u(2))&&S(a,b)&&w(a.h,new u(4,1))||Na(a)&&(Ja(a,b)||Ia(a,b))||Ma(a)&&(Q(a)||U(a))||Pa(a)&&(Q(a)||U(a))||("Chrome"===a.getName()&&1===v(a.n,new u(4,0,249))&&-1===v(a.n,new u(6))||0===v(a.n,new u(4,0,249))&&(a.n.j===k||4<=a.n.j))&&(Q(a)||U(a)||R(a))||"Chrome"===a.getName()&&
w(a.n,new u(6))&&(Ja(a,b)||Ia(a,b))||"AdobeAIR"===a.getName()&&w(a.n,new u(2,5))&&(P(a)&&a.h.e===k||U(a))},b:function(a){return Ma(a)&&R(a)||Oa(a)&&R(a)||Pa(a)&&R(a)||"AdobeAIR"===a.getName()&&w(a.n,new u(2,5))&&R(a)},d:function(a,b){return"Chrome"===a.getName()&&w(a.n,new u(6))&&(Q(a)||U(a)||R(a)||S(a,b)||"CrOS"===a.k||b.W&&"iPad"===a.k&&w(a.h,new u(5))||Ha(a,b)&&w(a.h,new u(5)))||"Gecko"===a.u&&1===v(a.z,new u(1,9,1))&&(Q(a)||U(a)||R(a)||S(a,b))||"Safari"===a.getName()&&("AppleWebKit"===a.u&&w(a.z,
new u(534,50)))&&(Q(a)||R(a))||Na(a)&&(b.W&&"iPad"===a.k&&w(a.h,new u(5))||Ha(a,b)&&w(a.h,new u(5)))||"Opera"===a.getName()&&w(a.n,new u(11,10))&&(Q(a)||U(a)||R(a)||S(a,b))||"MSIE"===a.getName()&&9<=a.N&&(P(a)&&w(a.h,new u(6,1))||P(a)&&0===v(a.h,new u(6,0)))||"MSIE"===a.getName()&&b.Oa&&"Windows Phone"===a.k&&w(a.h,new u(8))||Qa(a)&&b.pa&&"BlackBerry"===a.k&&w(a.h,new u(10))},f:function(a,b){return Qa(a)&&La(a,b)||b.K&&"Silk"===a.getName()&&w(a.n,new u(2))&&(La(a,b)||U(a))},i:function(a){return"MSIE"===
a.getName()&&(w(a.n,new u(6,0))&&(void 0===a.N||9>a.N))&&Q(a)}};function Va(a,b){var c=b||new Ga,d;for(d in Ta){var e=Ta[d];if(Ua[e](a,c))return e}return k}var Wa={};
Wa.i=new Ra(function(a,b,c){for(var d=0;d<b.length;d+=1){var e=b[d],f=a.replace(/(-1|-2)$/,"").slice(0,28)+"-"+e;c.push(new Fa(f,[e]))}a={};for(e=0;e<b.length;e++)c=b[e],d=c.charAt(1),(a[d]||(a[d]=[])).push(c);c=[[4,3,2,1,5,6,7,8,9],[7,8,9,6,5,4,3,2,1]];d=[];for(e=0;e<c.length;e++)for(var f=c[e],g=0;g<f.length;g++){var j=f[g];if(a[j]){d=d.concat(a[j]);break}}c=d;d={};a=[];for(e=0;e<c.length;e++)f=c[e],d[f]||(d[f]=h,a.push(f));c=[];for(d=0;d<b.length;d++){e=b[d];for(f=0;f<a.length;f++)g=a[f],g==e&&
c.push(g)}return c});var V={};V.a=V.b=V.d=function(){return[]};V.f=function(a){return[new Ca(a)]};V.i=function(a,b,c){return[new Ca(a),new Da(b,c)]};function W(a){this.g=a;this.ea=this.c=this.q=k;this.s=[];this.L=[];this.oa=this.U=k}function X(a){Y.s.push(a)}function Z(a){Y.L.push(a)}W.prototype.supportsConfiguredBrowser=function(){return!!this.q};
W.prototype.init=function(){if(0<this.L.length){for(var a=[],b=0;b<this.L.length;b++)a.push(Ba(this.L[b]));var b=this.g,a=a.join(""),c=this.g.createElement("style");c.setAttribute("type","text/css");c.styleSheet?c.styleSheet.cssText=a:c.appendChild(document.createTextNode(a));q(b,"head",c)}};
W.prototype.load=function(a,b){if(this.q){for(var c=Wa[this.q]||new Ra(Sa),d=0;d<this.s.length;d++){for(var e=this.s[d],f=this.q,g=c,j=[],p=e.F.split(",")[0].replace(/"|'/g,""),x=e.B(),fa=j,z=void 0,T=[],I={},oa=0;oa<x.length;oa++)z=x[oa],0<z.length&&!I[z]&&(I[z]=h,T.push(z));x=T;g=g.ma?g.ma(p,x,fa):x;e.ha[f]=g;e.ga[f]=j}if(this.U){c=V[this.q](this.g,this.q,this.s);d=this.q;e=[];for(f=0;f<c.length;f++)e.push(c[f].toString());var d=this.U.j("https:"===ja(this.g),{format:d,extras:e}),c=this.g,d=c.createElement("link",
{rel:"stylesheet",href:d}),$=l;d.onload=function(){$||($=h)};d.onerror=function(){$||($=h)};q(c,"head",d)}if(a){var pa=this,gb=this.q;ha(this.g,function(){for(var c=0;c<pa.s.length;c++)pa.s[c].$(a,gb,b&&c==pa.s.length-1)})}}};W.prototype.collectFontFamilies=function(a,b){if(this.q)for(var c=0;c<this.s.length;c++)Ea(this.s[c],this.q,a,b)};
W.prototype.performOptionalActions=function(){if(this.X){var a=this,b=this.c,c=this.g;ha(this.g,function(){var d=a.X;if(d.la){var e=window.__adobewebfontsappname__,e=e?e.toString().substr(0,20):"",d=d.la.j("https:"===ja(c),{host:encodeURIComponent(c.P.location.hostname||c.Y.location.hostname),app:encodeURIComponent(e),_:(+new Date).toString()}),f=new Image(1,1);f.src=d;f.onload=function(){f.onload=k}}d=a.X;d.da&&(d=d.da.j(b,c),q(c,"body",d))})}};
function Xa(a,b,c,d){this.Ga=a;this.g=b;this.c=c;this.l=d;this.r=[]}Xa.prototype.S=function(a){this.r.push(a)};Xa.prototype.load=function(a,b){var c=a,d=b||{};if("string"==typeof c)c=[c];else if(!c||!c.length)d=c||{},c=[];if(c.length)for(var e=this,f=c.length,g=0;g<c.length;g++){var j=this.Ga.j("https:"===ja(this.g),{id:encodeURIComponent(c[g])});ka(this.g,j,function(){0==--f&&Ya(e,d)})}else Ya(this,d)};
function Ya(a,b){if(0!=a.r.length){for(var c=new sa(a.g,a.l,b),d=l,e=0;e<a.r.length;e++)a.r[e].init(),d=d||a.r[e].supportsConfiguredBrowser();if(d){r(c.l,c.o.j(c.p,"loading"));F(c,"loading");for(var f=new L(a.c,a.g,c),c=function(a,b,c){for(var d=[],e=0;e<a.length;e+=1){var z=a[e];if(b[z])for(var T=b[z],I=0;I<T.length;I+=1)d.push(new H(z,T[I]));else d.push(new H(z))}f.$(d,{},k,c)},d=0;d<a.r.length;d++)e=a.r[d],e.supportsConfiguredBrowser()&&(e.load(c,d==a.r.length-1),e.performOptionalActions(window))}else ta(c);
a.r=[]}}function Za(a){this.ia=a;this.r=[]}Za.prototype.S=function(a){this.r.push(a)};Za.prototype.load=function(){var a=this.ia.__webfonttypekitmodule__;if(a)for(var b=0;b<this.r.length;b++){var c=this.r[b],d=a[c.oa];d&&d(function(a,b,d){a=[];b={};var j=(new ma(navigator.userAgent,document)).parse(),p=c;p.c=j;p.q=Va(p.c,p.ea);c.supportsConfiguredBrowser()&&(c.init(),c.load(k),c.collectFontFamilies(a,b),c.performOptionalActions(window));d(c.supportsConfiguredBrowser(),a,b)})}};
var $a=(new ma(navigator.userAgent,document)).parse();window.Typekit||(window.Typekit={});if(!window.Typekit.load){var ab=new Xa(new N("//typeface.nytimes.com/{id}.js"),new ga(window),$a,document.documentElement),bb=new Za(window);window.Typekit.load=function(){ab.load.apply(ab,arguments)};window.Typekit.addKit=function(){ab.S.apply(ab,arguments)}}var cb=k,db,Y,cb=new N("//p.typekit.net/p.gif?a=82618&f=387.388.389.390.391.392.397.399.401.403.404.405.413.18469.21702.22116.22118&h={host}&ht=sh&k=zam5nzz&s=1&_={_}");
db=new function(){var a=cb;this.da=k;this.la=a};Y=new W(new ga(window));Y.oa="zam5nzz";Y.U=new N("//typeface.nytimes.com/k/zam5nzz-{format}.css?3bb2a6e53c9684ffdc9a9bf3195b2a62d1c54ed00fc5de48ce5f634f4f883fc9df33b0edc8aa00545b01420738c515f9b1f54674d441a0eda2a177d123ad538bba88452292d4c8f8a12a849898dee9d6c45a04168e216be895357e42682f32cbcaa019917ae66160e78c0f6155142d128a4ac5fc937afb569467a097c30febc914edcb366ffde929966b33afbbb28e305837f1dc7f62636885");Y.X=db;X(new O("nyt-cheltenham","n2 n3 n4 n5 n7 i7".split(" ")));
X(new O("nyt-cheltenham-extra-cn-bd",["n7"]));X(new O("nyt-franklin","n3 i3 n5 i5 n7 i7".split(" ")));X(new O("nyt-stymie",["n7"]));X(new O("nyt-karnak-display-130124",["n4"]));X(new O("nyt-cheltenham-sh",["n4","n7"]));Z(new M([".tk-nyt-cheltenham"],[{value:'"nyt-cheltenham",sans-serif',name:"font-family"}]));Z(new M([".tk-nyt-cheltenham-extra-cn-bd"],[{value:'"nyt-cheltenham-extra-cn-bd",serif',name:"font-family"}]));Z(new M([".tk-nyt-franklin"],[{value:'"nyt-franklin",sans-serif',name:"font-family"}]));
Z(new M([".tk-nyt-stymie"],[{value:'"nyt-stymie",sans-serif',name:"font-family"}]));Z(new M([".tk-nyt-karnak-display-130124"],[{value:'"nyt-karnak-display-130124",sans-serif',name:"font-family"}]));Z(new M([".tk-nyt-cheltenham-sh"],[{value:'"nyt-cheltenham-sh",sans-serif',name:"font-family"}]));var eb;if(eb=bb)eb=!!bb.ia.__webfonttypekitmodule__;if(eb)bb.S(Y),bb.load();else{var fb=Y;fb.c=$a;fb.q=Va(fb.c,fb.ea);window.Typekit.addKit(Y)};
})(this,document);