############################################################
# Dockerfile to build splunk container
# Based on splunk:7.1.0
############################################################

# Set the base image to splunk:latest
FROM splunk/splunk:7.1.0

# Set the working directory
WORKDIR /opt/splunk

# File Author / Maintainer
MAINTAINER mkarnowski@avinetworks.com


################## BEGIN INSTALLATION ######################


# Install requirements
#RUN apt-get update
#RUN apt-get install -y vim

# Copy configurations to directory
COPY "web.conf" "/opt/splunk/etc/system/local/"
COPY "splunk.secret" "/opt/splunk/etc/auth/"
COPY "passwd" "/opt/splunk/etc/"
COPY "inputs.conf" "/opt/splunk/etc/apps/launcher/local/"
COPY "user-prefs.conf" "/opt/splunk/etc/users/admin/user-prefs/local/"
COPY "ui-tour.conf" "/opt/splunk/etc/system/local"
COPY ".ui_login" "/opt/splunk/etc/"
COPY "search-inputs.conf" "/opt/splunk/etc/apps/search/local/inputs.conf"

COPY TA-avi-vantage /opt/splunk/etc/apps/TA-avi-vantage

RUN chown splunk:splunk /opt/splunk/etc/system/local/web.conf
RUN chown -R splunk:splunk /opt/splunk/etc/apps/TA-avi-vantage
RUN chown splunk:splunk /opt/splunk/etc/auth/splunk.secret
RUN chown splunk:splunk /opt/splunk/etc/apps/launcher/local/inputs.conf
RUN chown splunk:splunk /opt/splunk/etc/users/admin/user-prefs/local/user-prefs.conf
RUN chown splunk:splunk /opt/splunk/etc/system/local/ui-tour.conf
RUN chown splunk:splunk /opt/splunk/etc/.ui_login
RUN chown splunk:splunk /opt/splunk/etc/apps/search/local/inputs.conf
