############################################################
# Dockerfile to build avi demo client
# Based on ubuntu:latest
############################################################

# Set the base image to ubuntu:latest
FROM ubuntu:16.04

WORKDIR /opt/avi/client



################## BEGIN INSTALLATION ######################

# Install client script requirements
RUN apt-get update
RUN apt-get upgrade -y
RUN apt-get install -y curl apache2-utils python-minimal python-requests dnsutils vim

# Copy Traffic Generation Script and dependencies

COPY "./traffic-kube.py" "/opt/avi/client/traffic-kube.py"

RUN chmod a+x /opt/avi/client/traffic-kube.py

# Execute script
#----NEED TO CREATE A START SCRIPT
CMD ["/usr/bin/python", "/opt/avi/client/traffic-kube.py"]
