

/** 
* @filepath: facebooklike,abc-events,calendar-event
* @created: Wed, 27 Nov 13 17:19:29 -0800
*/


/** 
* @filepath: /facebooklike/facebooklike.js
* @created: Wed, 27 Nov 13 17:19:29 -0800
*/

var abcdm=abcdm||{};abcdm.abccom=abcdm.abccom||{};abcdm.abccom.Utils=abcdm.abccom.Utils||{};(function($){$(document).ready(function(){$.each($('.abc-facebook-like iframe'),function(){var color,count;var param='';color=abcdm.abccom.Utils.convertHexToRgb($(this).parent());count=0;$.each(color,function(index,value){count=count+parseInt(value,10);});param+=(count>250)?"&colorscheme=dark":'';$(this).attr('src',$(this).attr('src')+param);});});}(jQuery));

/** 
* @filepath: /abcdm/abccom/eventdetect.js
* @created: Wed, 27 Nov 13 17:19:29 -0800
*/

var abcdm=abcdm||{abccom:{Utils:{}}};abcdm.abccom=abcdm.abccom||{};abcdm.abccom.Utils=abcdm.abccom.Utils||{};abcdm.abccom.Hook=abcdm.abccom.Hook||function(){};abcdm.abccom.debugLog=abcdm.abccom.debugLog||function(bug){return function(){};};(function($){$(document).ready(function(){var detectLog=abcdm.abccom.debugLog('event-detect'),imgObj={},imgData=$('.imageData').attr('title')||"",recapData,imgDataArray,epTimer,epTitle,defaultShow="",extractGalleryName=function(str){if(typeof str==="string"){str=str.slice(str.indexOf('/',1)+1,str.lastIndexOf('/'));}
return str;};abcdm.abccom.Hook('recapRead','debug');abcdm.abccom.Hook('recapRead',{'hook':function(obj){obj=obj||{};obj.context=obj.context||{};var recaps=$.secureEvalJSON($.cookie(obj.context.show+"recap"))||[];detectLog(obj);detectLog(obj.context.contentId);recaps.push(obj.context.contentId);detectLog(recaps);$.cookie(obj.context.show+"recap",$.toJSON(recaps));detectLog('dropped cookie'+obj.context.show);}});detectLog('init DR');epTitle=$.trim($('.episodeBrief .episodeTitle').text()).toLowerCase();if(typeof location.pathname.split('/')[2]==="string"&&$.inArray(location.pathname.split('/')[1],['shows','watch','movies','specials'])>-1){defaultShow=location.pathname.split('/')[2];}
if(epTitle){if(!$.cookie(defaultShow+"recap"))
{var recapData=[];}
else
{recapData=$.secureEvalJSON($.cookie(defaultShow+"recap"))||[];}
detectLog('recapData from cookie');detectLog(recapData);if($.inArray(epTitle,recapData)===-1){epTimer=setTimeout(function(){detectLog('in FUNC');abcdm.abccom.Hook('recapRead',{'args':{'context':{'show':defaultShow,'contentType':'recap','contentId':epTitle}}});},10000);}}
imgDataArray=imgData.split(',')||[];detectLog('before commentPostLoyalty');abcdm.abccom.Hook("commentPostSuccess",{'hook':function(obj){obj=obj||{};obj.context=obj.context||{};var defaultContentId="";if(typeof location.pathname.split('/')[2]==="string"&&$.inArray(location.pathname.split('/')[1],['shows','watch','movies','specials'])>-1){defaultContentId=location.pathname.slice(location.pathname.indexOf('/',1)+1);}
detectLog('defaultContentId');detectLog(defaultContentId);abcdm.abccom.Hook("commentPostLoyalty",{'args':{'context':{'show':defaultShow,'contentId':defaultContentId,'contentType':'comment'}}});}});abcdm.abccom.Hook("galleryView",{'hook':function(obj){obj=obj||{};obj.context=obj.context||{};if(typeof obj.context.show==="string"&&obj.context.contentCount===3){abcdm.abccom.Hook("galleryViewThreshold",{'args':obj});}else{detectLog('obj.context');detectLog(obj.context);}}});abcdm.abccom.Hook("galleryImageView",{'hook':function(obj){var imgCount=3,showName=obj.gallery.slice(0,obj.gallery.indexOf('-')),galleryData=$.secureEvalJSON($.cookie(showName+"gallery"))||{};detectLog(showName);detectLog(galleryData);detectLog(obj);detectLog(obj.gallery);galleryData[obj.gallery]=galleryData[obj.gallery]||[];if($.inArray(obj.imageName,galleryData[obj.gallery])===-1){detectLog('new pic viewed');galleryData[obj.gallery].push(obj.imageName);abcdm.abccom.Hook("galleryView",{'args':{'context':{'show':showName,'contentId':obj.gallery,'contentCount':galleryData[obj.gallery].length,'contentType':'gallery'}}});detectLog('cookie update '+showName+"gallery");$.cookie(showName+"gallery",$.toJSON(galleryData),{'path':'/','domain':'go.com'});}else{detectLog('pic found');detectLog(obj.gallery);detectLog(galleryData[obj.gallery]);}}});$.each(imgDataArray,function(){var tempPair=this.split('|');if((typeof tempPair[0]!=='undefined'&&typeof tempPair[1]!=='undefined')){tempPair[0]=$.trim(tempPair[0]);tempPair[1]=$.trim(tempPair[1]).replace(/\"/g,'&quot;');switch(tempPair[0]){case'gallery':imgObj.gallery=abcdm.abccom.Utils.contentIdFix(extractGalleryName(tempPair[1]));break;case'imageName':imgObj.imageName=abcdm.abccom.Utils.contentIdFix(tempPair[1]);break;case'imageTitle':imgObj.imageTitle=abcdm.abccom.Utils.contentIdFix(tempPair[1]);break;default:imgObj[tempPair[0]]=tempPair[1];}}});if(typeof imgObj.gallery==='string'&&typeof imgObj.imageName==='string'){detectLog(imgObj);abcdm.abccom.Hook("galleryImageView",{'args':imgObj});}});}(jQuery));

/** 
* @filepath: /community/social-link/calendar-event.js
* @created: Wed, 27 Nov 13 17:19:29 -0800
*/

var abcdm=abcdm||{abccom:{Utils:{}}};abcdm.abccom=abcdm.abccom||{};abcdm.abccom.SocialLink=abcdm.abccom.SocialLink||{};abcdm.abccom.SocialLink.calendar=abcdm.abccom.SocialLink.calendar||{};abcdm.abccom.Hook=abcdm.abccom.Hook||function(){};abcdm.abccom.debugLog=abcdm.abccom.debugLog||function(bug){return function(){};};(function($){var defaultProviders=['google','ical','outlook','yahoo'],defaultProvidersTitles=['Google Calendar','Apple iCal','Outlook Calendar','Yahoo! Calendar'],defaultReminderText='Add to your calendar by selecting one of the formats below.',googleUrl='http://www.google.com/calendar/event?action=TEMPLATE',yahooUrl='http://calendar.yahoo.com/?v=60&VIEW=d',fileDownloadUrl='http://ww2.abc.go.com/service/sociallink/get-calendar-file',buildGoogleUrl,buildYahooUrl,downloadFile,omniturePrepend="calendarevent:",calOmnitureTracking,zeroPad,overlayPopulated=false,calLog=abcdm.abccom.debugLog('calendar');abcdm.abccom.SocialLink.calendar.makeOverlay=function(eventdata,options){abcdm.abccom.Hook('hCalOpenOverlay');options=options||{};omniturePrepend=options.omnitureprepend?options.omnitureprepend:"calendarevent:";calOmnitureTracking(this,'calendaropenoverlay');var overlayw=options.width?options.width:355;var overlayh=options.height?options.height:300;$('#add-to-calendar-list').remove();var cssClass=options.customcsswrapper?' '+options.customcsswrapper:'';var reminderText=options.calendarremindertext?options.calendarremindertext:defaultReminderText;var providers=options.providers?options.providers:defaultProviders;var providerTitle=options.providersDesc?options.providersDesc:defaultProvidersTitles;$(document.body).append('<div id="add-to-calendar-list" class="overlaycontainer"><div class="overlaycontents calendarEvent'+cssClass+'"></div></div>');$('#add-to-calendar-list .calendarEvent').append('<h2>Add to Calendar</h2><h3>'+reminderText+'</h3><ul></ul>');for(var provider in providers){$('#add-to-calendar-list .calendarEvent ul').append('<li class="'+providers[provider]+'CalEvent">'
+'<a href="#" name="'+providers[provider]+'" title="Add this to your '+providerTitle[provider]+'">'
+providerTitle[provider]+'</a></li>');}
$('#add-to-calendar-list .calendarEvent ul li a').click(function(e){e.preventDefault();abcdm.abccom.SocialLink.calendar.addEvent(eventdata,this.name);});abcdm.abccom.Utils.createOverlay(overlayw,overlayh,'#add-to-calendar-list',true,10);};abcdm.abccom.SocialLink.calendar.addEvent=function(eventdata,provider){abcdm.abccom.Hook('hCalAddEvent');eventdata.enddate=eventdata.enddate?eventdata.enddate:eventdata.startdate;calOmnitureTracking(this,'calendaraddevent_'+provider);switch(provider){case'ical':case'outlook':downloadFile(eventdata,provider);break;case'google':buildGoogleUrl(eventdata);break;case'yahoo':buildYahooUrl(eventdata);break;}};buildGoogleUrl=function(eventdata){var calendarServiceCall=googleUrl;calendarServiceCall+='&text='+eventdata.title;calendarServiceCall+='&sprop='+eventdata.eventurl+'&sprop;=name:'+eventdata.title;calendarServiceCall+='&details='+eventdata.description;calendarServiceCall+='&dates='+eventdata.startdate+'/'+eventdata.enddate;if(eventdata.recurrence){calendarServiceCall+='&recur='+'RRULE:FREQ='+eventdata.recurrence.type+';INTERVAL='+eventdata.recurrence.interval+';UNTIL='+eventdata.recurrence.enddate;}
window.open(encodeURI(calendarServiceCall));};buildYahooUrl=function(eventdata){var calendarServiceCall=yahooUrl;calendarServiceCall+='&ST='+eventdata.startdate;calendarServiceCall+='&TITLE='+eventdata.title;calendarServiceCall+='&URL='+eventdata.eventurl;calendarServiceCall+='&DESC='+eventdata.description;if(eventdata.recurrence){var calFreq,calInterval;switch(eventdata.recurrence.type){case'DAILY':calFreq='DY';break;case'WEEKLY':calFreq='DY';break;case'MONTHLY':calFreq='DY';break;case'YEARLY':calFreq='DY';break;}
calInterval=zeroPad(eventdata.recurrence.interval,2);calendarServiceCall+='&RPAT='+calInterval+calFreq;calendarServiceCall+='&REND='+(eventdata.recurrence.enddate).substring(0,8);}
window.open(encodeURI(calendarServiceCall));};downloadFile=function(eventdata,provider){var calendarServiceCall=fileDownloadUrl+'?';calendarServiceCall+='sd='+eventdata.startdate;calendarServiceCall+='&ed='+eventdata.enddate;calendarServiceCall+='&desc='+eventdata.description;calendarServiceCall+='&t='+eventdata.title;calendarServiceCall+='&uri='+eventdata.eventurl;if(eventdata.recurrence){calendarServiceCall+='&rp='+eventdata.recurrence.type;calendarServiceCall+='&re='+eventdata.recurrence.enddate;calendarServiceCall+='&rf='+eventdata.recurrence.interval;}
calendarServiceCall+='&provider='+provider;window.location=encodeURI(calendarServiceCall);};calOmnitureTracking=function(element,val){try{s_omni.tl(element,'o',omniturePrepend+":"+val);}catch(e){calLog('error with tracking');}};zeroPad=function(num,count){var paddedNum=num+'';while(paddedNum.length<count){paddedNum="0"+paddedNum;}
return paddedNum;};}(jQuery));